package ui

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"charm.land/glamour/v2"
	"charm.land/glamour/v2/ansi"
	"charm.land/glamour/v2/styles"
	"charm.land/lipgloss/v2"
)

// trailingAnsiSpace matches trailing sequences of ANSI-wrapped spaces.
var trailingAnsiSpace = regexp.MustCompile(`(\x1b\[[0-9;]*m\s*)+$`)


// Styles for consistent CLI output.
// All colors use ANSI indices (0–15) so they adapt to the terminal's own palette
// and remain legible on both light and dark backgrounds.
var (
	Header = lipgloss.NewStyle().
		Bold(true).
		Padding(0, 1)

	Label = lipgloss.NewStyle().
		Bold(true)

	Dim = lipgloss.NewStyle().
		Faint(true)

	Success = lipgloss.NewStyle().
		Foreground(lipgloss.Color("2")) // ANSI green

	Warning = lipgloss.NewStyle().
		Foreground(lipgloss.Color("3")) // ANSI yellow

	Error = lipgloss.NewStyle().
		Foreground(lipgloss.Color("1")) // ANSI red

	Persona = lipgloss.NewStyle().
		Italic(true)

	NodeTitle = lipgloss.NewStyle().
			Bold(true)

	Role = lipgloss.NewStyle().
		Faint(true).
		Italic(true)

	Separator = lipgloss.NewStyle().
			Faint(true)
)

// theme holds the current light/dark setting. Defaults to "light".
var theme = "light"

// SetTheme sets the glamour rendering theme ("light" or "dark").
func SetTheme(t string) {
	if t == "light" || t == "dark" {
		theme = t
	}
}

// Theme returns the current theme.
func Theme() string {
	return theme
}

// DetectBackground is a no-op kept for call-site compatibility.
func DetectBackground() {}

// userStylePath is the location of a user-provided glamour style JSON,
// generated by the dotfiles theme system (theme:apply → generate:glamour).
const userStylePath = "~/.config/glamour/style.json"

// glamourOpts returns the glamour renderer option for the current theme.
// Priority: user style.json > built-in light/dark with backgrounds stripped.
func glamourOpts() glamour.TermRendererOption {
	expanded := expandTilde(userStylePath)
	if _, err := os.Stat(expanded); err == nil {
		return glamour.WithStylesFromJSONFile(expanded)
	}

	// Fallback: built-in style with backgrounds removed.
	var cfg ansi.StyleConfig
	if theme == "dark" {
		cfg = styles.DarkStyleConfig
	} else {
		cfg = styles.LightStyleConfig
	}
	cfg.H1.StylePrimitive.BackgroundColor = nil
	cfg.Code.StylePrimitive.BackgroundColor = nil
	if cfg.CodeBlock.Chroma != nil {
		cfg.CodeBlock.Chroma.Error.BackgroundColor = nil
		cfg.CodeBlock.Chroma.Background.BackgroundColor = nil
	}
	return glamour.WithStyles(cfg)
}

func expandTilde(p string) string {
	if len(p) > 0 && p[0] == '~' {
		if home, err := os.UserHomeDir(); err == nil {
			return home + p[1:]
		}
	}
	return p
}

// RenderMarkdown renders a markdown string with terminal formatting.
func RenderMarkdown(md string) (string, error) {
	r, err := glamour.NewTermRenderer(
		glamourOpts(),
		glamour.WithWordWrap(0),
	)
	if err != nil {
		return md, err
	}
	out, err := r.Render(md)
	if err != nil {
		return md, err
	}
	// Strip trailing whitespace that glamour pads to word-wrap width.
	lines := strings.Split(out, "\n")
	for i, line := range lines {
		line = strings.TrimRight(line, " ")
		line = trailingAnsiSpace.ReplaceAllString(line, "")
		lines[i] = line
	}
	return strings.Join(lines, "\n"), nil
}

// RenderMarkdownOrPlain tries to render markdown; falls back to plain text on error.
func RenderMarkdownOrPlain(md string) string {
	out, err := RenderMarkdown(md)
	if err != nil {
		return md
	}
	return out
}

// FormatNodeHeader renders a node title with metadata for walk output.
func FormatNodeHeader(title string, parent *string, role string, children, siblings []string, childRoles, siblingRoles map[string]string, crossRefs []string) string {
	var sb strings.Builder

	sb.WriteString(NodeTitle.Render(title))
	sb.WriteString("\n")

	if role != "" {
		sb.WriteString(Dim.Render("role: ") + Role.Render(role) + "\n")
	}

	if parent != nil {
		sb.WriteString(Dim.Render("parent: ") + *parent + "\n")
	} else {
		sb.WriteString(Dim.Render("parent: (none)") + "\n")
	}

	if len(children) > 0 {
		sb.WriteString(Dim.Render("children: ") + formatWithRoles(children, childRoles) + "\n")
	} else {
		sb.WriteString(Dim.Render("children: (none)") + "\n")
	}

	if len(siblings) > 0 {
		sb.WriteString(Dim.Render("siblings: ") + formatWithRoles(siblings, siblingRoles) + "\n")
	} else {
		sb.WriteString(Dim.Render("siblings: (none)") + "\n")
	}

	if len(crossRefs) > 0 {
		sb.WriteString(Dim.Render("cross-refs: ") + strings.Join(crossRefs, ", ") + "\n")
	} else {
		sb.WriteString(Dim.Render("cross-refs: (none)") + "\n")
	}

	sb.WriteString(Separator.Render(strings.Repeat("─", 60)) + "\n")

	return sb.String()
}

func formatWithRoles(titles []string, roles map[string]string) string {
	parts := make([]string, len(titles))
	for i, t := range titles {
		if r, ok := roles[t]; ok {
			parts[i] = t + " " + Role.Render("["+r+"]")
		} else {
			parts[i] = t
		}
	}
	return strings.Join(parts, ", ")
}

// FormatStep renders a step label for pipeline progress.
func FormatStep(fnName, stepName, nodeTitle string) string {
	return Label.Render(fmt.Sprintf("[%s]", fnName)) + " " +
		Dim.Render(stepName+" →") + " " +
		NodeTitle.Render(fmt.Sprintf("%q", nodeTitle))
}

// FormatPersona renders a persona label.
func FormatPersona(persona string) string {
	return Persona.Render(fmt.Sprintf("[%s]", persona))
}

// FormatCost renders a cost line.
func FormatCost(tokens int, cost float64, autoApproved bool, threshold float64) string {
	costStr := fmt.Sprintf("$%.4f", cost)
	tokStr := fmt.Sprintf("%d tokens", tokens)
	if autoApproved {
		return Dim.Render(fmt.Sprintf("[cost] %s, ~%s (auto-approved, below $%.2f)", tokStr, costStr, threshold))
	}
	return Warning.Render(fmt.Sprintf("[cost] %s, ~%s", tokStr, costStr))
}

// FormatOp renders a single file operation for display.
func FormatOp(action, name string) string {
	switch action {
	case "create":
		return Success.Render("  + ") + name
	case "edit":
		return Warning.Render("  ~ ") + name
	default:
		return "  " + action + ": " + name
	}
}

// FormatLogEntry renders a log entry for the log command.
func FormatLogEntry(timestamp, event, function, step, commit, note string) string {
	var sb strings.Builder
	sb.WriteString(Dim.Render("[" + timestamp + "]"))
	sb.WriteString(" ")

	switch event {
	case "completed":
		sb.WriteString(Success.Render(event))
	case "suggested":
		sb.WriteString(Warning.Render(event))
	case "accepted", "applied":
		sb.WriteString(Success.Render(event))
	case "rejected", "reverted":
		sb.WriteString(Error.Render(event))
	default:
		sb.WriteString(event)
	}

	if function != "" {
		sb.WriteString("  " + Label.Render(function))
	}
	if step != "" {
		sb.WriteString(Dim.Render(" → " + step))
	}
	if commit != "" {
		sb.WriteString(Dim.Render(fmt.Sprintf("  (%s)", commit)))
	}
	if note != "" {
		if len(note) > 60 {
			note = note[:60] + "..."
		}
		sb.WriteString(Dim.Render(fmt.Sprintf("  \"%s\"", note)))
	}

	return sb.String()
}

// PrepareStep holds one step's info for checklist rendering.
type PrepareStep struct {
	Name       string
	Gate       string
	Fn         string // delegation target
	MapOver    string
	Output     string
	Prompt     string // resolved prompt text
}

// PrepareData holds all data for rendering an agent task checklist.
type PrepareData struct {
	FnName       string
	NodeTitle    string
	Steps        []PrepareStep
	Parent       *string
	Siblings     []string
	Children     []string
	NeedsParent  bool
	NeedsSibling bool
	NeedsChild   bool
	CrossWalk    string
	ContextFiles []string
}

// RenderPrepareChecklist formats a function application as an agent task checklist.
func RenderPrepareChecklist(d PrepareData) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("[task] %s → %q\n", d.FnName, d.NodeTitle))
	if len(d.Steps) > 1 {
		names := make([]string, len(d.Steps))
		for i, s := range d.Steps {
			names[i] = s.Name
			if s.Gate != "" {
				names[i] += " (gate: " + s.Gate + ")"
			}
		}
		sb.WriteString(fmt.Sprintf("[pipeline] %d steps: %s\n", len(d.Steps), strings.Join(names, " → ")))
	}
	sb.WriteString("\n")

	// Target read
	sb.WriteString("[read] target\n")
	sb.WriteString(fmt.Sprintf("  $ sevens walk %q\n\n", d.NodeTitle))

	// Parent/siblings
	if d.Parent != nil {
		if d.NeedsParent {
			sb.WriteString("[read] parent\n")
			sb.WriteString(fmt.Sprintf("  $ sevens walk %q --depth 0\n\n", *d.Parent))
		}
		if d.NeedsSibling && len(d.Siblings) > 0 {
			sb.WriteString(fmt.Sprintf("[read] siblings (%d nodes)\n", len(d.Siblings)))
			for _, sib := range d.Siblings {
				sb.WriteString(fmt.Sprintf("  $ sevens walk %q --depth 0\n", sib))
			}
			sb.WriteString("\n")
		}
	}

	// Children
	if d.NeedsChild && len(d.Children) > 0 {
		sb.WriteString(fmt.Sprintf("[read] children (%d nodes)\n", len(d.Children)))
		for _, ch := range d.Children {
			sb.WriteString(fmt.Sprintf("  $ sevens walk %q --depth 0\n", ch))
		}
		sb.WriteString("\n")
	}

	// Cross-walk
	if d.CrossWalk != "" {
		sb.WriteString(fmt.Sprintf("[read] prior %s output (cross-walk)\n", d.CrossWalk))
		sb.WriteString(fmt.Sprintf("  $ sevens log %q  # find last %s output\n\n", d.NodeTitle, d.CrossWalk))
	}

	// Context files
	if len(d.ContextFiles) > 0 {
		sb.WriteString("[read] context files\n")
		for _, cf := range d.ContextFiles {
			sb.WriteString(fmt.Sprintf("  $ cat %s\n", cf))
		}
		sb.WriteString("\n")
	}

	// Steps
	for i, step := range d.Steps {
		if len(d.Steps) > 1 {
			sb.WriteString(fmt.Sprintf("[step %d: %s]\n", i+1, step.Name))
		}

		if step.Fn != "" {
			sb.WriteString(fmt.Sprintf("  [delegates to: %s]\n", step.Fn))
			if step.MapOver != "" {
				sb.WriteString(fmt.Sprintf("  [map-over: %s]\n", step.MapOver))
			}
			sb.WriteString(fmt.Sprintf("  $ sevens prepare %s %q  # for detailed sub-steps\n", step.Fn, d.NodeTitle))
		} else if step.Prompt != "" {
			sb.WriteString("[instruction]\n")
			for _, line := range strings.Split(step.Prompt, "\n") {
				sb.WriteString(fmt.Sprintf("  %s\n", line))
			}
		}
		sb.WriteString("\n")

		sb.WriteString(fmt.Sprintf("[output] %s\n", step.Output))
		sb.WriteString("[submit]\n")
		sb.WriteString(fmt.Sprintf("  $ sevens submit %q --function %s --step %s --output %s --response-file /tmp/%s-%s.txt\n",
			d.NodeTitle, d.FnName, step.Name, step.Output, d.FnName, step.Name))

		if step.Gate != "" {
			sb.WriteString(fmt.Sprintf("[gate] %s — review output, then:\n", step.Gate))
			sb.WriteString(fmt.Sprintf("  $ sevens accept %q\n", d.NodeTitle))
			sb.WriteString(fmt.Sprintf("  OR: $ sevens reject %q\n", d.NodeTitle))
		} else if i == len(d.Steps)-1 && step.Output == "ops" {
			sb.WriteString("[gate] review ops, then:\n")
			sb.WriteString(fmt.Sprintf("  $ sevens accept %q\n", d.NodeTitle))
			sb.WriteString(fmt.Sprintf("  OR: $ sevens reject %q\n", d.NodeTitle))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// FormatPending renders a pending suggestion entry.
// subject is the stable suspension ID (e.g. "suspension:<title>:<timestamp>");
// pass "" to omit it.
func FormatPending(target, function, step, summary, subject string) string {
	line := NodeTitle.Render(target)
	if function != "" {
		line += "  " + Dim.Render("(") + Label.Render(function)
		if step != "" {
			line += Dim.Render(" → "+step)
		}
		line += Dim.Render(")")
	}
	if summary != "" {
		line += "  " + Dim.Render(summary)
	}
	if subject != "" {
		// Show only the timestamp portion to keep the line compact.
		id := subject
		if parts := strings.SplitN(subject, ":", 3); len(parts) == 3 {
			id = parts[2]
		}
		line += "  " + Dim.Render("[id: "+id+"]")
	}
	return line
}
